### ISSUE TITLE
Not work with NextJS and Apollo Client

### ISSUE THREAD

**Issue by pdhung197** [funkhaus/wp-graphql-cors#25]
This is my setting in wordpress plugin:

<img width="697" alt="Screen Shot 2021-03-11 at 14 04 03" src="https://user-images.githubusercontent.com/14067307/110748677-a5887c00-8272-11eb-9f4d-03b43bab4427.png">

This is my code to create api client with Apollo Client:

```
const client = new ApolloClient({
  ssrMode: typeof window === "undefined",
  link: middleware.concat(
    afterware.concat(
      createHttpLink({
        uri: GRAPHQL_URL,
        fetch: fetch,
        credentials: "include",
        headers: {
          "Access-Control-Allow-Origin": true,
        },
      })
    )
  ),

  cache: new InMemoryCache(),
});
```

And this is what I received when I run the code:

```
{
  error: ApolloError: Response not successful: Received status code 500
      at new ApolloError (/MyCodePath/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
      at /MyCodePath/node_modules/@apollo/client/core/core.cjs.js:1490:19
      at /MyCodePath/node_modules/@apollo/client/utilities/utilities.cjs.js:958:69
      at new Promise (<anonymous>)
      at Object.error (/MyCodePath/node_modules/@apollo/client/utilities/utilities.cjs.js:958:21)
      at notifySubscription (/MyCodePath/node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (/MyCodePath/node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (/MyCodePath/node_modules/zen-observable/lib/Observable.js:240:7)
      at /MyCodePath/node_modules/@apollo/client/utilities/utilities.cjs.js:946:68
      at Array.forEach (<anonymous>)
      at iterateObserversSafely (/MyCodePath/node_modules/@apollo/client/utilities/utilities.cjs.js:946:25)
      at Object.error (/MyCodePath/node_modules/@apollo/client/utilities/utilities.cjs.js:1031:21)
      at notifySubscription (/MyCodePath/node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (/MyCodePath/node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (/MyCodePath/node_modules/zen-observable/lib/Observable.js:240:7)
      at Object.error (/MyCodePath/node_modules/zen-observable/lib/Observable.js:330:22) {
    graphQLErrors: [],
    networkError: Error [ServerError]: Response not successful: Received status code 500
        at Object.throwServerError (/MyCodePath/node_modules/@apollo/client/link/utils/utils.cjs.js:45:17)
        at /MyCodePath/node_modules/@apollo/client/link/http/http.cjs.js:32:19
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      response: [Response],
      statusCode: 500,
      result: [Object]
    },
    extraInfo: undefined
  }
}
```
 
If I uncheck **Block unauthorized domains** checkbox, CORS not work and I can fetch data from localhost:1355, 1353 or whatever.
Did I do something's wrong here? How can I fix this?

**Comment by drewbaker** [comment]
Just pushed a new version that fixes a lot of issues. Want to give that a try?
